# Generated by Django 4.1.7 on 2023-03-26 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Slider",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("image", models.ImageField(upload_to="slider/")),
                ("title", models.CharField(max_length=100)),
                ("destination_link", models.TextField(default="#")),
                ("alt_data", models.CharField(max_length=200)),
                ("post_date", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
