# Generated by Django 4.1.6 on 2023-04-01 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Slider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("banner", models.ImageField(upload_to="slider")),
                ("slug", models.SlugField(blank=True, null=True)),
                ("destination", models.CharField(default="#", max_length=250)),
            ],
        ),
    ]
